
spring:
  thymeleaf:
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://localhost:3306/dbgirl?useSSL=false
    username: root
    password: 123456
    tomcat:
      max-active: 20
      max-idle: 10
      min-idle: 5
      initial-size: 5
      max-wait: 10000
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    favicon:
      enabled: true
server:
  port: 8030
  session:
    timeout: 10
  tomcat:
    uri-encoding: utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml



